# Generated by Django 4.2 on 2026-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('OCR', 'OCR'), ('MANUAL', 'Manual')], default='OCR', max_length=10)),
                ('status', models.CharField(default='extracted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
