# Generated by Django 4.2 on 2026-01-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/back/'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/front/'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='pan/'),
        ),
    ]
